initramfs-android-image: increase INITRAMFS_MAXSIZE
* Otherwise wicenv fails with:
  ERROR: initramfs-android-image-1.0-r0 do_rootfs_wicenv: The initramfs size 209672(K) overrides INITRAMFS_MAXSIZE: 131072(K)
  ERROR: initramfs-android-image-1.0-r0 do_rootfs_wicenv: You can set INITRAMFS_MAXSIZE a larger value. Usually, it should
  ERROR: initramfs-android-image-1.0-r0 do_rootfs_wicenv: be less than 1/2 of ram size, or you may fail to boot it.

  ERROR: initramfs-android-image-1.0-r0 do_rootfs_wicenv: Function failed: set_image_size
  ERROR: Logfile of failure stored in: /home/jenkins/workspace/luneos-unstable/webos-ports/tmp-glibc/work/mako-webos-linux-gnueabi/initramfs-android-image/1.0-r0/temp/log.do_rootfs_wicenv.4695
  NOTE: recipe initramfs-android-image-1.0-r0: task do_rootfs_wicenv: Failed
* The reported size is BS, it's still around 8MB, so this is only
  temporary work around until wicenv is fixed to measure used
  disk space correctly

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>