linux-palmpre: bump PE to fix upgrade path after branch change
* changing branch resets LOCALCOUNT and causes
  ERROR: Package version for package kernel-headers went backwards which
  would break package feeds from
  (0:2.6.24+gitr4+dc2ff991a816e51847cc5edd0bbbf19d1600ad49-r3 to
   0:2.6.24+gitr2+dc2ff991a816e51847cc5edd0bbbf19d1600ad49-r3)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>