initscripts: fix bbappends
* there was still MACHINE variable used in do_install
* fixes:
ERROR: initscripts different signature for task do_populate_sysroot.sigdata between qemux86copy and qemux86
runtaskdeps changed from ['initscriptsinitscripts_1.0.bb.do_install'] to ['initscriptsinitscripts_1.0.bb.do_install']
openembedded-core/meta/recipes-core/initscripts/initscripts_1.0.bb.do_install with hash a6c1cea4a425254e4b12ca7fcc86d066
 changed to
openembedded-core/meta/recipes-core/initscripts/initscripts_1.0.bb.do_install with hash 320945aee8e3d13d2a5fbbeb45e546e6
Hash for dependent task initscriptsinitscripts_1.0.bb.do_install changed from a6c1cea4a425254e4b12ca7fcc86d066 to 320945aee8e3d13d2a5fbbeb45e546e6

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>