Revert "sensorfw: Split to keep layers clean"
This reverts commit 7c0245048f031fdaeaca3af8dc5e5d9188b7fb78.

meta-android doesn't depend on meta-webos-ports/meta-luneos where
sensorfw recipe is and IMHO it shouldn't.

fixes:
ERROR: No recipes in default available for: /OE/build/oe-core/meta-smartphone/meta-android/recipes-support/sensorfw/sensorfw.bbappend
in builds without meta-webos-ports/meta-luneos layer.

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>