meta-android-halium.inc: blacklist virglrenderer, cogl-1.0, clutter-1.0, mx-1.0, clutter-gst-3.0, clutter-gtk-1.0
fixes:
ERROR: Nothing PROVIDES 'mesa' (but /OE/build/luneos-warrior/webos-ports/openembedded-core/meta/recipes-graphics/virglrenderer/virglrenderer_0.7.0.bb DEPENDS on or otherwise requires it)
mesa was skipped: PREFERRED_PROVIDER_virtual/libgl set to mesa-gl, not mesa
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'virglrenderer', 'mesa']

and

ERROR: Nothing RPROVIDES 'libgles2' (but /OE/build/luneos-warrior/webos-ports/openembedded-core/meta/recipes-graphics/cogl/cogl-1.0_1.22.2.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'libgles2' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['libgles2']
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'mx-1.0', 'clutter-1.0', 'cogl-1.0', 'libgles2']

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>