initramfs-android-image: make sure that ANDROID_EXTRA_INITRAMFS_IMAGE_INSTALL is expanded
* e.g. for hammerhead it's empty and causes:

ERROR: Nothing RPROVIDES '${ANDROID_EXTRA_INITRAMFS_IMAGE_INSTALL}' (but /OE/build/luneos-sumo/webos-ports/meta-smartphone/meta-android/recipes-core/images/initramfs-android-image.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target '${ANDROID_EXTRA_INITRAMFS_IMAGE_INSTALL}' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['${ANDROID_EXTRA_INITRAMFS_IMAGE_INSTALL}']
NOTE: Runtime target 'android-kernel-bootimg' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['android-kernel-bootimg', 'initramfs-android-image', '${ANDROID_EXTRA_INITRAMFS_IMAGE_INSTALL}']
NOTE: Runtime target 'luneos-dev-package-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['luneos-dev-package-dev', 'luneos-dev-image', 'android-kernel-bootimg', 'initramfs-android-image', '${ANDROID_EXTRA_INITRAMFS_IMAGE_INSTALL}']
NOTE: Runtime target 'luneos-dev-package' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['luneos-dev-package', 'luneos-dev-image', 'android-kernel-bootimg', 'initramfs-android-image', '${ANDROID_EXTRA_INITRAMFS_IMAGE_INSTALL}']
NOTE: Runtime target 'luneos-dev-image' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['luneos-dev-image', 'android-kernel-bootimg', 'initramfs-android-image', '${ANDROID_EXTRA_INITRAMFS_IMAGE_INSTALL}']
NOTE: Runtime target 'android-kernel-bootimg-dev' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['android-kernel-bootimg-dev', 'initramfs-android-image', '${ANDROID_EXTRA_INITRAMFS_IMAGE_INSTALL}']
ERROR: Nothing RPROVIDES 'initramfs-android-image'
No eligible RPROVIDERs exist for 'initramfs-android-image'
NOTE: Runtime target 'initramfs-android-image' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['initramfs-android-image']

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>