Revert "linux-lg-mako: bump SRCREV"
This reverts commit e036f3506e4b0157b9cca44cf26cb894f265448e.

It made things worse:
| /home/jenkins/workspace/luneos-unstable/webos-ports/tmp-glibc/work-shared/mako/kernel-source/include/linux/rcupdate.h:
In function '__kfree_rcu':
| /home/jenkins/workspace/luneos-unstable/webos-ports/tmp-glibc/work-shared/mako/kernel-source/include/linux/rcupdate.h:917:2:
error: size of unnamed array is negative
|   BUILD_BUG_ON(!__builtin_constant_p(offset));
|   ^

Possibly related to:
http://lkml.iu.edu/hypermail/linux/kernel/1105.1/01251.html