samsung-rfs-mgr: add dependency on systemd
* otherwise when systemd isn't detected in do_configure:
  Package systemd was not found in the pkg-config search path.
  Perhaps you should add the directory containing `systemd.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'systemd' found

  do_package fails with:
  ERROR: samsung-rfs-mgr-0.1.0+gitrAUTOINC+db81eaaed9-r2 do_package:
  Function failed: SYSTEMD_SERVICE_samsung-rfs-mgr value
  samsung-rfs-mgr.service does not exist

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>