meta-android-halium.inc: don't blacklist virglrenderer
* it now depends on virtual/libgl, so it can be built with mesa-gl as well, since oe-core change:
  commit ddbe09b0f9861fe3012611b5a5298eb4d7c4df45
  Author: Chandana kalluri <ckalluri@xilinx.com>
  Date:   Wed Aug 12 15:34:45 2020 -0700

    qemu.inc: Use virtual/libgl instead of mesa

    Use virtual/libgl instead of mesa within the recipes to provide users the
    flexibility to specify providers other than mesa.

* target qemu still won't build with this configuration:
  | /OE/build/luneos-master/webos-ports/tmp-glibc/work/aarch64-halium-webos-linux/qemu/5.1.0-r0/qemu-5.1.0/ui/gtk-egl.c:50:5: error: unknown type name 'Window'; did you mean 'AtkWindow'?
  |    50 |     Window x11_window = gdk_x11_window_get_xid(gdk_window);
  |       |     ^~~~~~
  |       |     AtkWindow
  |   LINK    fsdev/virtfs-proxy-helper
  |   LINK    scsi/qemu-pr-helper
  | /OE/build/luneos-master/webos-ports/tmp-glibc/work/aarch64-halium-webos-linux/qemu/5.1.0-r0/qemu-5.1.0/ui/gtk-egl.c: In function 'gtk_egl_init':
  | /OE/build/luneos-master/webos-ports/tmp-glibc/work/aarch64-halium-webos-linux/qemu/5.1.0-r0/qemu-5.1.0/ui/gtk-egl.c:292:5: error: unknown type name 'Display'; did you mean 'EGLDisplay'?
  |   292 |     Display *x11_display = gdk_x11_display_get_xdisplay(gdk_display);
  |       |     ^~~~~~~
  |       |     EGLDisplay

  but at least it won't cause signature issue shown in:
  http://jenkins.nas-admin.org/job/LuneOS/view/unstable/job/luneos-unstable_workspace-compare-signatures/90/console

  ERROR: Nothing PROVIDES 'virglrenderer' (but /home/jenkins/workspace/luneos-unstable/webos-ports/openembedded-core/meta/recipes-devtools/qemu/qemu_5.1.0.bb DEPENDS on or otherwise requires it)
  virglrenderer was skipped: Recipe is blacklisted: Depends on mesa and mesa isn't available because mesa-gl is preferred provider of virtual/libgl
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'qemu', 'virglrenderer']

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>