tenderloin: remove libhybris bbappend to use newer one
* like other halium MACHINEs now

14:31 <+JaMa> Herrie: any plans to upgrade libhybris revision on tenderloin? it's now failing with:
14:31 <+JaMa> sync.c:24:10: fatal error: linux/sync.h: No such file or directory
14:31 <+JaMa> and it builds fine on e.g. tissot, so I guess that it's because older SRCREV we use here
14:32 <+Herrie> JaMa: There were some issues previously, this is why we were stuck on older one
14:32 <+JaMa> # fix libhybris revision to an older version, as there is a serious memory leak
14:32 <+JaMa> # in more recent ones, which still needs to be analyzed
14:32 <+Herrie> But seeing we're on newer Android those might have gone
14:32 <+Herrie> Also libhybris had some fixes
14:32 <+Herrie> So we can try to remove the bbappend simply
14:34 <+JaMa> https://github.com/libhybris/libhybris/commit/352c01859207491b5c8f1eb684bff8872d11a447 or backport this to older
14:36 <+Herrie> Let's just remove the bbappend for now
14:36 <+Herrie> If the memory leak is still there we can simply go back
14:37 <+Herrie> So many things got fixed over time, I suspect the memory leak might be gone... https://github.com/libhybris/libhybris/pulls?q=is%3Apr+is%3Aclosed
14:38 <+JaMa> it builds without the bbappend, so it's an improvement already :)

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>