libhybris: provide virtual/libgles3 as well
* mesa provides it since:
  https://git.openembedded.org/openembedded-core/commit/?id=405cd7a37988ced627fe6ad6fd3089c17f59367e
  and kmscube explicitly depends on it since:
  https://git.openembedded.org/openembedded-core/commit/?id=a8bac1006d87d0a702630607f6c46d2f4926776e

* libhybris does provide gles3 headers and libs, so add that as well to avoid:
ERROR: Nothing PROVIDES 'virtual/libgles3' (but /OE/build/luneos-nanbield/openembedded-core/meta/recipes-graphics/kmscube/kmscube_git.bb DEPENDS on or otherwise requires it)
mesa PROVIDES virtual/libgles3 but was skipped: PREFERRED_PROVIDER_virtual/libgl set to mesa-gl, not mesa
ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'kmscube', 'virtual/libgles3']

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>