android-tools: exclude android-tools-conf dependency with SIGGEN_EXCLUDE_SAFE_RECIPE_DEPS
* see:
  http://lists.openembedded.org/pipermail/openembedded-devel/2015-September/103271.html
* fixes:
ERROR: android-tools different signature for task do_package_write_ipk.sigdata between qemux86copy and qemux86
runtaskdeps changed from ['android-toolsandroid-tools-conf_1.0.bb.do_packagedata', 'android-toolsandroid-tools_4.2.2.bb.do_package', 'android-toolsandroid-tools_4.2.2.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native'] to ['android-toolsandroid-tools-conf_1.0.bb.do_packagedata', 'android-toolsandroid-tools_4.2.2.bb.do_package', 'android-toolsandroid-tools_4.2.2.bb.do_packagedata', 'opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native']
meta-smartphone/meta-android/recipes-android/android-tools/android-tools-conf_1.0.bb.do_packagedata with hash bfd6f69ad976d411e4a5073b55df74ad
 changed to
meta-smartphone/meta-android/recipes-android/android-tools/android-tools-conf_1.0.bb.do_packagedata with hash abe3c0d07d6704d9693885e33eaa0fb8
Hash for dependent task android-toolsandroid-tools-conf_1.0.bb.do_packagedata changed from bfd6f69ad976d411e4a5073b55df74ad to abe3c0d07d6704d9693885e33eaa0fb8

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>