shr-version: Add weak assignment for DISTRO_RELEASE
* it fails for distro-less or !SHR builds

DEBUG: Executing shell function do_configure
/home/jenkins/oe/shr-core-branches/shr-core/tmp-eglibc/work/qemux86_64-oe-linux/shr-version/${DISTRO_RELEASE}-r0/temp/run.do_configure.29970:
89: cd: can't cd to
/home/jenkins/oe/shr-core-branches/shr-core/tmp-eglibc/work/qemux86_64-oe-linux/shr-version/-r0/shr-version-

NOTE: recipe shr-version-${DISTRO_RELEASE}-r0: task do_populate_lic: Started
ERROR: Error executing a python function in /home/jenkins/oe/shr-core-branches/shr-core/meta-smartphone/meta-shr/recipes-shr/shr/shr-version.bb:

The stack trace of python calls that resulted in this exception/failure was:
File: 'sstate_task_postfunc', lineno: 14, function: <module>
     0010:    sstate_package(shared_state, d)
     0011:    os.umask(omask)
     0012:
     0013:
 *** 0014:sstate_task_postfunc(d)
     0015:
File: 'sstate_task_postfunc', lineno: 4, function: sstate_task_postfunc
     0001:
     0002:def sstate_task_postfunc(d):
     0003:    shared_state = sstate_state_fromvars(d)
 *** 0004:    sstate_install(shared_state, d)
     0005:    for intercept in shared_state['interceptfuncs']:
     0006:        bb.build.exec_func(intercept, d)
     0007:    omask = os.umask(002)
     0008:    if omask != 002:
File: 'sstate.bbclass', lineno: 77, function: sstate_install
     0073:
     0074:    # Run the actual file install
     0075:    for state in ss['dirs']:
     0076:        if os.path.exists(state[1]):
 *** 0077:            oe.path.copyhardlinktree(state[1], state[2])
     0078:
     0079:    for postinst in (d.getVar('SSTATEPOSTINSTFUNCS', True) or '').split():
     0080:        bb.build.exec_func(postinst, d)
     0081:
File: '/home/jenkins/oe/shr-core-branches/shr-core/openembedded-core/meta/lib/oe/path.py', lineno: 97, function: copyhardlinktree
     0093:    if (os.stat(src).st_dev ==  os.stat(dst).st_dev):
     0094:        # Need to copy directories only with tar first since cp will error if two
     0095:        # writers try and create a directory at the same time
     0096:        cmd = 'cd %s; find . -type d -print | tar -cf - -C %s -ps --files-from - | tar -xf - -C %s' % (src, src, dst)
 *** 0097:        check_output(cmd, shell=True, stderr=subprocess.STDOUT)
     0098:        if os.path.isdir(src):
     0099:            src = src + "/*"
     0100:        cmd = 'cp -afl %s %s' % (src, dst)
     0101:        check_output(cmd, shell=True, stderr=subprocess.STDOUT)
File: '/home/jenkins/oe/shr-core-branches/shr-core/openembedded-core/meta/lib/oe/path.py', lineno: 164, function: check_output
     0160:    if retcode:
     0161:        cmd = kwargs.get("args")
     0162:        if cmd is None:
     0163:            cmd = popenargs[0]
 *** 0164:        raise CalledProcessError(retcode, cmd, output=output)
     0165:    return output
     0166:
     0167:def find(dir, **walkoptions):
     0168:    """ Given a directory, recurses into that directory,
Exception: CalledProcessError: Command 'cd /home/jenkins/oe/shr-core-branches/shr-core/tmp-eglibc/work/qemux86_64-oe-linux/shr-version/${DISTRO_RELEASE}-r0/license-destdir; find . -type d -print | tar -cf - -C /home/jenkins/oe/shr-core-branches/shr-core/tmp-eglibc/work/qemux86_64-oe-linux/shr-version/${DISTRO_RELEASE}-r0/license-destdir -ps --files-from - | tar -xf - -C /home/jenkins/oe/shr-core-branches/shr-core/tmp-eglibc/deploy/licenses' returned non-zero exit status 2 with output /bin/sh: 1: cd: can't cd to /home/jenkins/oe/shr-core-branches/shr-core/tmp-eglibc/work/qemux86_64-oe-linux/shr-version/-r0/license-destdir
tar: /home/jenkins/oe/shr-core-branches/shr-core/tmp-eglibc/work/qemux86_64-oe-linux/shr-version/-r0/license-destdir: Cannot chdir: No such file or directory
tar: Error is not recoverable: exiting now
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors

ERROR: Function failed: sstate_task_postfunc
ERROR: Logfile of failure stored in: /home/jenkins/oe/shr-core-branches/shr-core/tmp-eglibc/work/qemux86_64-oe-linux/shr-version/${DISTRO_RELEASE}-r0/temp/log.do_populate_lic.30139
NOTE: recipe shr-version-${DISTRO_RELEASE}-r0: task do_populate_lic: Failed

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>