qi: move PROVIDES from .inc to qi_git.bb
* fixes (in this case) harmless error during image build
  ERROR: Multiple .bb files are due to be built which each provide virtual/bootloader
  it's just alternative to qi, so it's ok to build both and user will download one of them

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>