linux-nokia900-meego: update defconfig
disable SMIA_SENSOR because of:
| drivers/media/video/smia-sensor.c:858:2: error: unknown field 's_config' specified in initializer
| drivers/media/video/smia-sensor.c:858:2: warning: initialization from incompatible pointer type [enabled by default]
| drivers/media/video/smia-sensor.c:858:2: warning: (near initialization for 'smia_core_ops.g_chip_ident') [enabled by default]
| drivers/media/video/smia-sensor.c: In function 'smia_probe':
| drivers/media/video/smia-sensor.c:954:22: error: 'MEDIA_PAD_FL_OUTPUT' undeclared (first use in this function)
| drivers/media/video/smia-sensor.c:954:22: note: each undeclared identifier is reported only once for each function it appears in

and enable USB_MUSB_OMAP2PLUS to fix:
| drivers/built-in.o: In function `musb_probe':
| clkdev.c:(.init.text+0x5594): undefined reference to `dma_controller_create'
| drivers/built-in.o: In function `musb_free':
| clkdev.c:(.text.unlikely+0x11a8): undefined reference to `dma_controller_destroy'
"

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>