icon-theme-neo: inherit allarch
* see:
  http://lists.openembedded.org/pipermail/openembedded-devel/2015-September/103271.html
* fixes:
ERROR: shr-theme-neo different signature for task do_package_write_ipk.sigdata between qemux86copy and qemuarm
runtaskdeps changed from ['opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'themese-wm-theme-illume-neo_git.bb.do_packagedata', 'themeselementary-theme-neo_git.bb.do_packagedata', 'themesgpe-theme-neo_git.bb.do_packagedata', 'themesgtk-theme-neo_git.bb.do_packagedata', 'themesicon-theme-neo_git.bb.do_packagedata', 'themesphoneui-shr-theme-neo_git.bb.do_packagedata', 'themesshr-theme-neo.bb.do_package', 'themesshr-theme-neo.bb.do_packagedata'] to ['opkg-utilsopkg-utils_git.bb.do_populate_sysroot:virtual:native', 'pseudopseudo_1.7.4.bb.do_populate_sysroot:virtual:native', 'themese-wm-theme-illume-neo_git.bb.do_packagedata', 'themeselementary-theme-neo_git.bb.do_packagedata', 'themesgpe-theme-neo_git.bb.do_packagedata', 'themesgtk-theme-neo_git.bb.do_packagedata', 'themesicon-theme-neo_git.bb.do_packagedata', 'themesphoneui-shr-theme-neo_git.bb.do_packagedata', 'themesshr-theme-neo.bb.do_package', 'themesshr-theme-neo.bb.do_packagedata']
meta-smartphone/meta-shr/recipes-shr/themes/icon-theme-neo_git.bb.do_packagedata with hash 8128065345fce15cafa3f004deeb7d72
 changed to
meta-smartphone/meta-shr/recipes-shr/themes/icon-theme-neo_git.bb.do_packagedata with hash 30d48a224c3890e07cedfbb47f9a0575
Hash for dependent task themesicon-theme-neo_git.bb.do_packagedata changed from 8128065345fce15cafa3f004deeb7d72 to 30d48a224c3890e07cedfbb47f9a0575

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>